// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPafyw95wm6_kNPA9RVJKVk1rWxuJPPuU',
    appId: '1:973813386336:web:192a7cdc1ec0ac60564705',
    messagingSenderId: '973813386336',
    projectId: 'events3-b9fb8',
    authDomain: 'events3-b9fb8.firebaseapp.com',
    storageBucket: 'events3-b9fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxliQbSy7Lc2c0ZfTgtqYKn_tGiYuxi0',
    appId: '1:973813386336:android:18db5261c177ac0a564705',
    messagingSenderId: '973813386336',
    projectId: 'events3-b9fb8',
    storageBucket: 'events3-b9fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfGQHh8UffdCmu75YlicQpEqDwDwkJH8',
    appId: '1:973813386336:ios:e8ac34bcc3f0299e564705',
    messagingSenderId: '973813386336',
    projectId: 'events3-b9fb8',
    storageBucket: 'events3-b9fb8.appspot.com',
    iosClientId: '973813386336-37mqgfs854mtov79jfk13qir9ho5jf4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.events3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfGQHh8UffdCmu75YlicQpEqDwDwkJH8',
    appId: '1:973813386336:ios:e8ac34bcc3f0299e564705',
    messagingSenderId: '973813386336',
    projectId: 'events3-b9fb8',
    storageBucket: 'events3-b9fb8.appspot.com',
    iosClientId: '973813386336-37mqgfs854mtov79jfk13qir9ho5jf4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.events3',
  );
}
